### ISSUE TITLE
Use Programaticly

### ISSUE THREAD

**Issue by halilyuce** [iamshezad/SHSelections#1]
Hi bro, thanks for this pod but I need your help. I have an endpoint and there is some questions which has multiple and single selection types. I must to show all of questions and finally I need selected answers index and that answer`s question indexpath too.

> "questions": [
{
"index": 0,
"description": "Sigara kullanıyor musunuz?",
"options": [
{
"id": 1,
"value": "Evet",
"selected": false
},
{
"id": 2,
"value": "Hayır",
"selected": false
}
],
"type": "single"
},
{
"index": 1,
"description": "Ücret beklentiniz ne kadar?",
"options": [
{
"id": 1,
"value": "1000-2000",
"selected": false
},
{
"id": 2,
"value": "2000-3000",
"selected": false
},
{
"id": 3,
"value": "5000-10000",
"selected": false
}
],
"type": "multiple"
},
{
"index": 2,
"description": "Esnek çalışma saatlerine uygun musunuz?",
"options": [
{
"id": 1,
"value": "Evet",
"selected": false
},
{
"id": 2,
"value": "Hayır",
"selected": false
},
{
"id": 3,
"value": "Belki",
"selected": false
}
],
"type": "single"
}
]
},

How can I show this questions and how can I get every question and answers index seperatly for post answers to api.

<img width="378" alt="ekran resmi 2019-01-04 16 35 21" src="https://user-images.githubusercontent.com/29376592/50690541-c0318b80-103e-11e9-9b01-fdb3bc75ae03.png">

**Comment by iamshezad** [comment]
@halilyuce Hi, I suggest you use SHSelections inside a tableView cell and use section header for questions.

**Comment by halilyuce** [comment]
Thanks for suggestion and reply, I solved it :)
